[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  publish = "public"


[[plugins]]
package = "netlify-plugin-image-optim"
[[plugins]]
  package = "netlify-plugin-algolia-index"
  [plugins.inputs]
      exclude = ['''^\/admin.*''', '''^\/search.*''', '/404.html']
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
      